services:
  php-app:
    build: .
    volumes:
      - .:/app
      - ~/.ssh:/home/appuser/.ssh:ro
    working_dir: /app
    user: "${UID}:${GID}"
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
      XDEBUG_MODE: "${XDEBUG_MODE}"
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"
      MYSQL_HOST: "${MYSQL_HOST:-db}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-chess}"
      MYSQL_USER: "${MYSQL_USER:-chess}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-chess}"
    ports:
      - "8000:80"
    command: php-fpm
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chess
      MYSQL_USER: chess
      MYSQL_PASSWORD: chess
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
