services:
  php:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    user: "${UID}:${GID}"
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
      XDEBUG_MODE: "${XDEBUG_MODE}"
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"
    ports:
      - "8000:80"
    command: php-fpm
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
